"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import z from "zod";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

export const THEME_OPTIONS = [
  { value: "modern-dark", label: "Modern Dark (Slate & Cyan)" },
  { value: "executive-navy", label: "Executive Navy (Navy & Gold)" },
  { value: "corporate-blue", label: "Corporate Blue (Clean & Blue)" },
  { value: "minimalist-light", label: "Minimalist Light (Neutral & Indigo)" },
  { value: "emerald", label: "Emerald (Dark Green & Mint)" },
  {
    value: "powerpoint-orange",
    label: "PowerPoint Classic (Signature Orange)",
  },
] as const;

const formSchema = z.object({
  variableName: z
    .string()
    .min(1, { message: "Variable name is required" })
    .regex(/^[A-Za-z_$][A-Za-z0-9_$]*$/, {
      message:
        "Variable name must start with a letter or underscore and contain only letters, numbers, and underscores",
    }),
  title: z.string().min(1, { message: "Presentation title is required" }),
  subtitle: z.string().optional(),
  author: z.string().optional(),
  theme: z.enum([
    "modern-dark",
    "executive-navy",
    "corporate-blue",
    "minimalist-light",
    "emerald",
    "powerpoint-orange",
  ]),
  content: z.string().optional(),
});

export type PowerPointFormValues = z.infer<typeof formSchema>;

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSubmit: (values: PowerPointFormValues) => void;
  defaultValues?: Partial<PowerPointFormValues>;
}

export const PowerPointDialog = ({
  open,
  onOpenChange,
  onSubmit,
  defaultValues = {},
}: Props) => {
  const form = useForm<PowerPointFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      variableName: defaultValues.variableName || "presentation",
      title: defaultValues.title || "Automated Presentation",
      subtitle: defaultValues.subtitle || "Generated by OtogentAI",
      author: defaultValues.author || "OtogentAI Workflow",
      theme:
        (defaultValues.theme as PowerPointFormValues["theme"]) || "modern-dark",
      content:
        defaultValues.content ||
        "# Slide 1: Executive Summary\n- High-level business overview\n- Strategic deliverables and impact\n\n# Slide 2: Key Milestones\n- Rapid workflow automation\n- Direct PowerPoint file generation",
    },
  });

  useEffect(() => {
    if (open) {
      form.reset({
        variableName: defaultValues.variableName || "presentation",
        title: defaultValues.title || "Automated Presentation",
        subtitle: defaultValues.subtitle || "Generated by OtogentAI",
        author: defaultValues.author || "OtogentAI Workflow",
        theme:
          (defaultValues.theme as PowerPointFormValues["theme"]) ||
          "modern-dark",
        content:
          defaultValues.content ||
          "# Slide 1: Executive Summary\n- High-level business overview\n- Strategic deliverables and impact\n\n# Slide 2: Key Milestones\n- Rapid workflow automation\n- Direct PowerPoint file generation",
      });
    }
  }, [open, defaultValues, form]);

  const handleSubmit = (values: PowerPointFormValues) => {
    onSubmit(values);
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-3">
            {/* biome-ignore lint/performance/noImgElement: local static svg icon */}
            <img
              src="/powerpoint.svg"
              alt="Microsoft PowerPoint"
              className="size-7 object-contain"
            />
            <div>
              <DialogTitle>Microsoft PowerPoint Node</DialogTitle>
              <DialogDescription>
                Configure automated PowerPoint (.pptx) presentation generation.
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(handleSubmit)}
            className="space-y-4"
          >
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="variableName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Output Variable Name</FormLabel>
                    <FormControl>
                      <Input placeholder="presentation" {...field} />
                    </FormControl>
                    <FormDescription className="text-xs">
                      Access in downstream nodes via{" "}
                      <code>{`{{${field.value || "presentation"}.base64}}`}</code>{" "}
                      or{" "}
                      <code>{`{{${field.value || "presentation"}.dataUrl}}`}</code>
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="theme"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Visual Theme</FormLabel>
                    <Select
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select a theme" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {THEME_OPTIONS.map((theme) => (
                          <SelectItem key={theme.value} value={theme.value}>
                            {theme.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormDescription className="text-xs">
                      High-definition 16:9 widescreen layout & styling
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="title"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Presentation Title</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="e.g. {{topic}} or Q3 Business Review"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="subtitle"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Subtitle / Tagline (Optional)</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="e.g. {{summary}} or Strategic Overview"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="author"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Presenter / Author Tag (Optional)</FormLabel>
                  <FormControl>
                    <Input
                      placeholder="e.g. Prepared for Leadership Team"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="content"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>
                    Slides Content (Markdown, Bullets, or JSON)
                  </FormLabel>
                  <FormControl>
                    <Textarea
                      rows={7}
                      placeholder={`Pass AI node output like {{openaiResponse}} or write markdown:\n\n# Slide Title\n## Subtitle\n- First key point\n- Second key point`}
                      className="font-mono text-xs"
                      {...field}
                    />
                  </FormControl>
                  <FormDescription className="text-xs space-y-1">
                    <span>
                      💡 You can connect an <strong>OpenAI</strong>,{" "}
                      <strong>Gemini</strong>, or <strong>Claude</strong> node
                      before this and pass <code>{`{{openaiResponse}}`}</code>{" "}
                      directly into this field!
                    </span>
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <DialogFooter className="mt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
              >
                Cancel
              </Button>
              <Button type="submit">Save Changes</Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};
