"use client";

import { ChevronDown } from "lucide-react";
import { useState } from "react";

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: "What is Otogent AI and how does it work?",
    answer:
      "Otogent AI is an autonomous AI launchpad that helps founders design, architect, code, and deploy production-ready startups entirely through conversation. Autonomous AI agents coordinate across the full development lifecycle to take your idea from concept to market-ready product with zero friction.",
  },
  {
    question:
      "How can a single person build a billion-dollar company with Otogent AI?",
    answer:
      "Otogent AI acts as your tireless co-founding team. It pairs you with specialized autonomous agents handling software architecture, backend engineering, pixel-perfect frontend design, CI/CD deployment, security, and automated growth marketing—allowing one founder to output the velocity of a 50-person tech company.",
  },
  {
    question: "Do I need coding experience to use Otogent AI?",
    answer:
      "No technical background is required. You can guide your project using natural language prompts. If you are an experienced software engineer, Otogent AI gives you granular control over code structures, frameworks, API integrations, and continuous deployment environments.",
  },
  {
    question: "Do I own the source code and intellectual property?",
    answer:
      "Yes, 100%. You retain full intellectual property ownership of every line of code, asset, database schema, and deployment configuration generated by Otogent AI. You can export clean code repositories or host them anywhere without vendor lock-in.",
  },
  {
    question: "How do I get started with my startup launch?",
    answer:
      "Click on 'Take-Off your Startup' or 'Sign up' in the navigation bar to start immediately. Outline your vision in the prompt workspace, and your autonomous team will begin prototyping and deploying your application within minutes.",
  },
];

export function LandingFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section
      id="faq"
      className="py-20 sm:py-28 px-6 sm:px-12 md:px-20 lg:px-28 bg-[#fbfbf9] dark:bg-[#141414] border-t border-neutral-200/60 dark:border-neutral-800/60 font-[-apple-system,BlinkMacSystemFont,'SF_Pro_Text','SF_Pro_Display',system-ui,sans-serif]"
    >
      <div className="max-w-3xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-12 sm:mb-16">
          <div className="inline-flex items-center gap-1.5 px-3.5 py-1 rounded-full bg-blue-50 dark:bg-blue-950/50 border border-blue-200 dark:border-blue-800/50 text-blue-600 dark:text-blue-400 text-[12px] font-semibold mb-3 tracking-tight">
            <span>Frequently Asked Questions</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-neutral-900 dark:text-neutral-50 mb-4">
            Everything you need to know
          </h2>
          <p className="text-neutral-500 dark:text-neutral-400 text-[15px] sm:text-[16px] max-w-xl mx-auto">
            Learn how Otogent AI empowers founders to build, launch, and scale
            their one-person billion-dollar startup.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={faq.question}
                className={`bg-white dark:bg-[#1e1e1e] rounded-2xl border transition-all duration-200 p-5 sm:p-6 shadow-[0_2px_8px_rgba(0,0,0,0.03)] ${
                  isOpen
                    ? "border-neutral-300 dark:border-neutral-700 shadow-[0_4px_16px_rgba(0,0,0,0.06)]"
                    : "border-neutral-200/70 dark:border-neutral-800"
                }`}
              >
                <button
                  type="button"
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex items-center justify-between text-left select-none group focus:outline-none"
                >
                  <span className="text-[15px] sm:text-[16.5px] font-semibold text-neutral-900 dark:text-neutral-100 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors pr-4">
                    {faq.question}
                  </span>
                  <span
                    className={`shrink-0 w-8 h-8 rounded-full flex items-center justify-center transition-colors ${
                      isOpen
                        ? "bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-400"
                        : "bg-neutral-100 text-neutral-600 dark:bg-neutral-800 dark:text-neutral-400 group-hover:bg-blue-50 group-hover:text-blue-600 dark:group-hover:bg-blue-950 dark:group-hover:text-blue-400"
                    }`}
                  >
                    <ChevronDown
                      className={`w-4 h-4 transition-transform duration-200 ${
                        isOpen ? "rotate-180" : ""
                      }`}
                    />
                  </span>
                </button>
                {isOpen && (
                  <div className="pt-4 text-[14px] sm:text-[14.5px] leading-relaxed text-neutral-600 dark:text-neutral-300 border-t border-neutral-100 dark:border-neutral-800 mt-4">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
